---

- name: install vim and related packages
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - build-essential
    - cmake
    - python-dev
    - vim
  tags: vim

- name: create the vim user and fonts directory
  file:
    path: "{{ item[0] }}"
    state: directory
    recurse: yes
  become: yes
  become_user: "{{ item[1] }}"
  with_nested:
    - - "~/.vim/bundle"
      - "~/.fonts"
    - "{{ vim_users }}"
  tags: vim

- name: download vundle and powerline fonts
  git:
    repo: "{{ vim_vundle_url }}"
    dest: "~/.vim/bundle/Vundle.vim"
    accept_hostkey: yes
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ vim_users }}"
  tags: vim

- name: create the .vimrc file
  template:
    src: vimrc.j2
    dest: "~/.vimrc"
    backup: yes
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ vim_users }}"
  tags: vim

- name: create global alias to install vim plugins
  lineinfile:
    dest: /etc/bash.bashrc
    line: "alias vpi='vim +PluginInstall +qall'"
    state: present
  tags: vim

